/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiCrawlRouteImport } from './routes/api/crawl'
import { Route as ApiAnalyzeRouteImport } from './routes/api/analyze'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCrawlRoute = ApiCrawlRouteImport.update({
  id: '/api/crawl',
  path: '/api/crawl',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAnalyzeRoute = ApiAnalyzeRouteImport.update({
  id: '/api/analyze',
  path: '/api/analyze',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/analyze': typeof ApiAnalyzeRoute
  '/api/crawl': typeof ApiCrawlRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/analyze': typeof ApiAnalyzeRoute
  '/api/crawl': typeof ApiCrawlRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/analyze': typeof ApiAnalyzeRoute
  '/api/crawl': typeof ApiCrawlRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/analyze' | '/api/crawl'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/analyze' | '/api/crawl'
  id: '__root__' | '/' | '/api/analyze' | '/api/crawl'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiAnalyzeRoute: typeof ApiAnalyzeRoute
  ApiCrawlRoute: typeof ApiCrawlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/crawl': {
      id: '/api/crawl'
      path: '/api/crawl'
      fullPath: '/api/crawl'
      preLoaderRoute: typeof ApiCrawlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/analyze': {
      id: '/api/analyze'
      path: '/api/analyze'
      fullPath: '/api/analyze'
      preLoaderRoute: typeof ApiAnalyzeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiAnalyzeRoute: ApiAnalyzeRoute,
  ApiCrawlRoute: ApiCrawlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
